apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: fs
  namespace: openshift-local-storage
spec:
  logLevel: Normal
  managementState: Managed
  storageClassDevices:
    - devicePaths:
        - /dev/sdc
      fsType: ext4
      storageClassName: local-storage
      volumeMode: Filesystem
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 447Gi      
