apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: femto-data-store
  namespace: sftp-noroot
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  #storageClassName: local-storage
