apiVersion: v1
data:
  ssh_host_ed25519_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    .......
    .......
    .......
    .......
    -----END OPENSSH PRIVATE KEY-----
  ssh_host_ed25519_key.pub: |
    ssh-ed25519 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxx
  ssh_host_rsa_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ............
    ............
    ............
    ............
    -----END OPENSSH PRIVATE KEY-----
  ssh_host_rsa_key.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDyGJBAixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  sshd_config: |
    Protocol 2
    HostKey /opt/ssh/ssh_host_ed25519_key
    HostKey /opt/ssh/ssh_host_rsa_key
    UseDNS no
    PermitRootLogin no
    X11Forwarding no
    AllowTcpForwarding no
    Subsystem sftp internal-sftp
    ForceCommand internal-sftp
    LogLevel DEBUG3
    Port 2022
    PidFile /opt/ssh/sshd.pid
    ChallengeResponseAuthentication no
    UsePAM yes
kind: ConfigMap
metadata:
  name: sftp-ava-ssh
  namespace: sftp-noroot
